apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: kinetocare # Spațiul izolat de lucru al aplicației
spec:
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: api-gateway
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: kinetocare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: kinetocare/api-gateway:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: kinetocare-config
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"
          ports:
            - containerPort: 8081
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 120
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe: # Verifică dacă aplicația e "vie". Dacă nu, k8s o restartează automat
            tcpSocket:
              port: 8081
            initialDelaySeconds: 150 # Pornit mai târziu decât readinessProbe
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
