apiVersion: v1
kind: Secret # Tipul resursei: Secret (pentru date sensibile ca parole/keys)
metadata:
  name: kinetocare-secrets
  namespace: kinetocare # Spațiul izolat de lucru al aplicației
type: Opaque # Tip de date generic (binar/text)
stringData: # Folosim stringData pentru a scrie parolele în clar (k8s le va codifica automat în base64)
  MYSQL_ROOT_PASSWORD: "Emma19"
  MYSQL_PASSWORD: "Emma19"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  RABBITMQ_PASS: "guest"
