apiVersion: v1
kind: Service # Tipul resursei: Service (un Load Balancer intern)
metadata:
  name: user-service # Numele unic. Alte servicii îl vor găsi la http://user-service:8082
  namespace: kinetocare # Spațiul izolat de lucru al aplicației
spec:
  ports:
    - port: 8082 # Portul pe care Service-ul îl expune (cel "văzut" de alte servicii)
      targetPort: 8082 # Portul real pe care rulează aplicația în interiorul containerului
  selector:
    app: user-service # Spune Service-ului care containere aparțin de el
  type: ClusterIP # Accesibil doar din interiorul clusterului
---
apiVersion: apps/v1
kind: Deployment # Tipul resursei: Deployment (managerul de containere)
metadata:
  name: user-service
  namespace: kinetocare
spec:
  replicas: 1 # Câte copii (Pods) ale aplicației să ruleze constant
  selector:
    matchLabels:
      app: user-service # k8s monitorizează containerele cu acest label
  template: # Descrierea containerului propriu-zis
    metadata:
      labels:
        app: user-service # Label-ul care "leagă" acest container de Service-ul de mai sus
    spec:
      containers:
        - name: user-service
          image: kinetocare/user-service:latest # Imaginea Docker generată
          imagePullPolicy: IfNotPresent # Nu descarcă imaginea dacă există local
          envFrom: # Ia TOATE variabilele din ConfigMap și le pune ca env variables
            - configMapRef:
                name: kinetocare-config
          env: # Definire individuală pentru variabile sensibile (secrete)
            - name: MYSQL_PASSWORD # Numele variabilei citite de Java
              valueFrom:
                secretKeyRef:
                  name: kinetocare-secrets # Caută în fișierul de Secrets...
                  key: MYSQL_PASSWORD # ...valoarea după această cheie
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"
          ports:
            - containerPort: 8082
          readinessProbe: # Verifică dacă aplicația e gata să primească trafic
            httpGet:
              path: /actuator/health # Endpoint-ul de verificare (Spring Boot Actuator)
              port: 8082
            initialDelaySeconds: 60 # Așteaptă 60 secunde la început (Java pornește mai greu)
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe: # Verifică dacă aplicația e "vie". Dacă nu, k8s o restartează automat
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 90 # Pornit mai târziu decât readinessProbe
            periodSeconds: 15
            failureThreshold: 3
          resources: # Gestionarea resurselor de sistem
            requests:
              memory: "128Mi" # Rezervă minimul de RAM
            limits:
              memory: "384Mi" # Limita maximă de RAM admisă
