spring:
  application:
    name: programare
    boot:
      admin:
        client:
          url: http://localhost:8080
          username: admin
          password: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.myapp.user: DEBUG
    org.springframework.cloud.netflix: DEBUG